#!/bin/bash

MAIN="main.go"

if [[ $1 == -* ]]
then
    go run src/$MAIN $@
elif [[ $1 == "build" || $1 == "run" ]]
then
    go build -o target src/$MAIN

    if [[ $1 == "run" ]]
    then
        "./target/${MAIN%.*}" "${@:2}"
    fi
elif [[ $1 == "test" || $1 == "quest" ]]
then
    FLAG=true

    for IN_FILE in $(find tests/$2/ -name "*.in")
    do
        ANS_FILE="${IN_FILE%.*}.ans"
        if diff -u --suppress-common-lines --label $ANS_FILE --label $2 --strip-trailing-cr -d --speed-large-files --color $ANS_FILE <(go run src/$MAIN --solution $2 < $IN_FILE)
        then
            echo -e "\033[0;32m$IN_FILE aye!\033[0m"
        else
            echo -e "\033[0;31m$IN_FILE nay!\033[0m"
            FLAG=false
        fi
    done

    echo ""

    if [[ $FLAG == true ]]
    then
        echo -e "\033[0;32m$JAVA_FILE passes!\033[0m"
    else
        echo -e "\033[0;31m$JAVA_FILE vetoed!\033[0m"
    fi
elif [[ $1 == "init" ]]
then
    mkdir -p src/solutions/${2%/*}
    cp hello.go src/solutions/$2
elif [[ $1 == "clean" ]]
then
    rm -r target/*
else
    echo "Usage: algo_owls --solution <SOLUTION>"
    echo ""
    echo "For more information, try '--help'."
fi
